### ISSUE TITLE
Remove the dependency on Flutter

### ISSUE THREAD

**Issue by f-person** [ivofernandes/spell_check_on_client#1]
Hey there! It seems that this package doesn't really use Flutter in any way so it'd probably make sense to remove the dependency on Flutter and make it a pure Dart package :)

**Comment by Clothless** [comment]
Which dependency do you want to remove?

**Comment by f-person** [comment]
flutter dependencies:

1. https://github.com/ivofernandes/spell_check_on_client/blob/master/pubspec.yaml#L12
2. https://github.com/ivofernandes/spell_check_on_client/blob/master/pubspec.yaml#L16
3. https://github.com/ivofernandes/spell_check_on_client/blob/master/pubspec.yaml#L18

**Comment by ivofernandes** [comment]
This one can be easily removed, will publish the drop now
https://github.com/ivofernandes/spell_check_on_client/blob/master/pubspec.yaml#L12

Probably the dev dependencies will not bother anyone, will it?

https://github.com/ivofernandes/spell_check_on_client/blob/master/pubspec.yaml#L16
https://github.com/ivofernandes/spell_check_on_client/blob/master/pubspec.yaml#L18

But if you don't want them on dev_dependencies try a PR with the tests passing

**Comment by f-person** [comment]
> Probably the dev dependencies will not bother anyone, will it?

Nope, I don't think they will :) 
Also, they don't depend on Flutter itself, these are pure Dart packages :)
